AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters: 
  Stage:
    Type: String
    AllowedValues:
      - dev
      - qa
      - demo
      - prod
  ProjectName:
    Type: String

# Mappings:
#   Stages:
#     dev:
#     qa:
#     demo:
#     prod:

Resources: